import "./globals.scss";
import "./index.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
// import style from "../../styles/css/index.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Geeks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="body">
        <div>
          <Navbar />
        </div>
        <div className="children">{children}</div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
